package com.gzzn.fgw.model;
// Generated 2014-2-13 15:35:02 by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;import javax.persistence.GenerationType;import javax.persistence.SequenceGenerator;
import javax.persistence.GeneratedValue;import javax.persistence.GenerationType;import javax.persistence.SequenceGenerator;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SysOperationlog generated by hbm2java
 */
@Entity
@Table(name="sys_operatorlog"
    
)
public class SysOperatorlog  implements java.io.Serializable {


     private Integer operationlogRecId;
     private SysUser sysUser;
     private SysDept sysDept;
     private SysOrganization sysOrganization;
     private byte[] operationContent;
     private Date operationDatetime;

    public SysOperatorlog() {
    }

    public SysOperatorlog(SysUser sysUser, SysDept sysDept, SysOrganization sysOrganization, byte[] operationContent, Date operationDatetime) {
       this.sysUser = sysUser;
       this.sysDept = sysDept;
       this.sysOrganization = sysOrganization;
       this.operationContent = operationContent;
       this.operationDatetime = operationDatetime;
    }
   
     @Id@SequenceGenerator(name="generator", sequenceName="xmsb",allocationSize = 1) @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="generator")

    
    @Column(name="operationlog_rec_id", unique=true, nullable=false)
    public Integer getOperationlogRecId() {
        return this.operationlogRecId;
    }
    
    public void setOperationlogRecId(Integer operationlogRecId) {
        this.operationlogRecId = operationlogRecId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public SysUser getSysUser() {
        return this.sysUser;
    }
    
    public void setSysUser(SysUser sysUser) {
        this.sysUser = sysUser;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dept_id")
    public SysDept getSysDept() {
        return this.sysDept;
    }
    
    public void setSysDept(SysDept sysDept) {
        this.sysDept = sysDept;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="organization_id")
    public SysOrganization getSysOrganization() {
        return this.sysOrganization;
    }
    
    public void setSysOrganization(SysOrganization sysOrganization) {
        this.sysOrganization = sysOrganization;
    }
    
    @Column(name="operation_content")
    public byte[] getOperationContent() {
        return this.operationContent;
    }
    
    public void setOperationContent(byte[] operationContent) {
        this.operationContent = operationContent;
    }

    
    @Column(name="operation_datetime", length=19)
    public Date getOperationDatetime() {
        return this.operationDatetime;
    }
    
    public void setOperationDatetime(Date operationDatetime) {
        this.operationDatetime = operationDatetime;
    }


}


