package com.gzzn.fgw.model;
// Generated 2014-2-13 15:35:02 by Hibernate Tools 3.2.4.GA


import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;import javax.persistence.GenerationType;import javax.persistence.SequenceGenerator;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * XmsbDwtxl generated by hbm2java
 */
@Entity
@Table(name="xmsb_dwtxl"
    
)
public class XmsbDwtxl  implements java.io.Serializable {


     private Integer dwtxlId;
     private SysOrganization sysOrganization;
     private String lxrmc;
     private String sjhm;
     private String email;
     private String lxdz;
     private String cz;
     private String dh;
     private Integer js;

    public XmsbDwtxl() {
    }

	
    public XmsbDwtxl(Integer dwtxlId) {
        this.dwtxlId = dwtxlId;
    }
    public XmsbDwtxl(Integer dwtxlId, SysOrganization sysOrganization, String lxrmc, String sjhm, String email, String lxdz, String cz, String dh, Integer js) {
       this.dwtxlId = dwtxlId;
       this.sysOrganization = sysOrganization;
       this.lxrmc = lxrmc;
       this.sjhm = sjhm;
       this.email = email;
       this.lxdz = lxdz;
       this.cz = cz;
       this.dh = dh;
       this.js = js;
    }
   
    @Id@SequenceGenerator(name="generator", sequenceName="xmsb",allocationSize = 1) @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="generator")
    @Column(name="DWTXL_ID", unique=true, nullable=false, scale=0)
    public Integer getDwtxlId() {
        return this.dwtxlId;
    }
    
    public void setDwtxlId(Integer dwtxlId) {
        this.dwtxlId = dwtxlId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="organization_id")
    public SysOrganization getSysOrganization() {
        return this.sysOrganization;
    }
    
    public void setSysOrganization(SysOrganization sysOrganization) {
        this.sysOrganization = sysOrganization;
    }

    
    @Column(name="LXRMC", length=50)
    public String getLxrmc() {
        return this.lxrmc;
    }
    
    public void setLxrmc(String lxrmc) {
        this.lxrmc = lxrmc;
    }

    
    @Column(name="SJHM", length=20)
    public String getSjhm() {
        return this.sjhm;
    }
    
    public void setSjhm(String sjhm) {
        this.sjhm = sjhm;
    }

    
    @Column(name="EMAIL", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="LXDZ", length=100)
    public String getLxdz() {
        return this.lxdz;
    }
    
    public void setLxdz(String lxdz) {
        this.lxdz = lxdz;
    }

    
    @Column(name="CZ", length=20)
    public String getCz() {
        return this.cz;
    }
    
    public void setCz(String cz) {
        this.cz = cz;
    }

    
    @Column(name="DH", length=20)
    public String getDh() {
        return this.dh;
    }
    
    public void setDh(String dh) {
        this.dh = dh;
    }

    
    @Column(name="JS", precision=1, scale=0)
    public Integer getJs() {
        return this.js;
    }
    
    public void setJs(Integer js) {
        this.js = js;
    }




}


